@Library('mylibrary')_
pipeline
{
    agent any
    stages
    {
        stage('ContDownload')
        {
            steps
            {
                script
                {
                    cicd.gitdownload("Maven345")
                }
            }
        }
        stage('contBuild')
        {
            steps
            {
                script
                {
                    cicd.mavenbuild()
                }
            }
        }
        stage('ContDeploy')
        {
            steps
            {
                script
                {
                    cicd.deploy("Sharedlib","172.31.12.246","testapp")
                }
            }
        }
        
    }
}
