@Library('mylibrary')_
pipeline
{
    agent any
    stages
    {
        stage('ContinuousDownload_Master')
        {
            steps
            {
                script
                {
                    cicd.gitdownload("Maven345")
                }
            }
        }
        stage('continuousBuild_Master')
        {
            steps
            {
                script
                {
                    cicd.mavenbuild()
                }
            }
        }
        stage('ContinuousDeploy_Master')
        {
            steps
            {
                script
                {
                    cicd.deploy("Sharedlib","172.31.12.246","testapp")
                }
            }
        }
        stage('ContinuousTesting_Master')
        {
            steps
            {
                script
                {
                    cicd.gitdownload("Testing")
                    cicd.runSelenium("Sharedlib")
                }
            }
        }
        stage('ContinuousDelivery_Master')
        {
            steps
            {
                script
                {
                    cicd.deploy("Sharedlib","172.31.3.129","prod")
                }
            }
        }
    }
}
